name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build shortener
      run: go build -v ./cmd/shortener/main.go -o shortener
    
    - name: Build redirector
      run: go build -v ./cmd/redirector/main.go -o redirector

    - name: Test
      run: go test -v ./...
